package com.konfigthis.client;

import com.konfigthis.client.api.AccessControlHandlerApi;
import com.konfigthis.client.api.AccessTokenValidatorApi;
import com.konfigthis.client.api.AccountStatusNotificationHandlerApi;
import com.konfigthis.client.api.AlarmManagerApi;
import com.konfigthis.client.api.AlertHandlerApi;
import com.konfigthis.client.api.AttributeSyntaxApi;
import com.konfigthis.client.api.AzureAuthenticationMethodApi;
import com.konfigthis.client.api.BackendApi;
import com.konfigthis.client.api.CertificateMapperApi;
import com.konfigthis.client.api.ChangeSubscriptionApi;
import com.konfigthis.client.api.ChangeSubscriptionHandlerApi;
import com.konfigthis.client.api.CipherSecretKeyApi;
import com.konfigthis.client.api.CipherStreamProviderApi;
import com.konfigthis.client.api.ClientConnectionPolicyApi;
import com.konfigthis.client.api.ConjurAuthenticationMethodApi;
import com.konfigthis.client.api.ConnectionCriteriaApi;
import com.konfigthis.client.api.ConnectionHandlerApi;
import com.konfigthis.client.api.ConsentDefinitionApi;
import com.konfigthis.client.api.ConsentDefinitionLocalizationApi;
import com.konfigthis.client.api.ConsentServiceApi;
import com.konfigthis.client.api.ConstructedAttributeApi;
import com.konfigthis.client.api.CorrelatedLdapDataViewApi;
import com.konfigthis.client.api.CryptoManagerApi;
import com.konfigthis.client.api.CustomLoggedStatsApi;
import com.konfigthis.client.api.DataSecurityAuditorApi;
import com.konfigthis.client.api.DebugTargetApi;
import com.konfigthis.client.api.DelegatedAdminAttributeApi;
import com.konfigthis.client.api.DelegatedAdminAttributeCategoryApi;
import com.konfigthis.client.api.DelegatedAdminCorrelatedRestResourceApi;
import com.konfigthis.client.api.DelegatedAdminResourceRightsApi;
import com.konfigthis.client.api.DelegatedAdminRightsApi;
import com.konfigthis.client.api.DnMapApi;
import com.konfigthis.client.api.EntryCacheApi;
import com.konfigthis.client.api.ExtendedOperationHandlerApi;
import com.konfigthis.client.api.ExternalServerApi;
import com.konfigthis.client.api.FailureLockoutActionApi;
import com.konfigthis.client.api.GaugeApi;
import com.konfigthis.client.api.GaugeDataSourceApi;
import com.konfigthis.client.api.GlobalConfigurationApi;
import com.konfigthis.client.api.GroupImplementationApi;
import com.konfigthis.client.api.HttpConfigurationApi;
import com.konfigthis.client.api.HttpServletCrossOriginPolicyApi;
import com.konfigthis.client.api.HttpServletExtensionApi;
import com.konfigthis.client.api.IdTokenValidatorApi;
import com.konfigthis.client.api.IdentityMapperApi;
import com.konfigthis.client.api.InterServerAuthenticationInfoApi;
import com.konfigthis.client.api.JsonAttributeConstraintsApi;
import com.konfigthis.client.api.JsonFieldConstraintsApi;
import com.konfigthis.client.api.KeyManagerProviderApi;
import com.konfigthis.client.api.KeyPairApi;
import com.konfigthis.client.api.LdapCorrelationAttributePairApi;
import com.konfigthis.client.api.LdapSdkDebugLoggerApi;
import com.konfigthis.client.api.LicenseApi;
import com.konfigthis.client.api.LocalDbCompositeIndexApi;
import com.konfigthis.client.api.LocalDbIndexApi;
import com.konfigthis.client.api.LocalDbVlvIndexApi;
import com.konfigthis.client.api.LocationApi;
import com.konfigthis.client.api.LogFieldBehaviorApi;
import com.konfigthis.client.api.LogFieldMappingApi;
import com.konfigthis.client.api.LogFieldSyntaxApi;
import com.konfigthis.client.api.LogFileRotationListenerApi;
import com.konfigthis.client.api.LogPublisherApi;
import com.konfigthis.client.api.LogRetentionPolicyApi;
import com.konfigthis.client.api.LogRotationPolicyApi;
import com.konfigthis.client.api.MacSecretKeyApi;
import com.konfigthis.client.api.MatchingRuleApi;
import com.konfigthis.client.api.MonitorProviderApi;
import com.konfigthis.client.api.MonitoringEndpointApi;
import com.konfigthis.client.api.NotificationManagerApi;
import com.konfigthis.client.api.OauthTokenHandlerApi;
import com.konfigthis.client.api.ObscuredValueApi;
import com.konfigthis.client.api.OtpDeliveryMechanismApi;
import com.konfigthis.client.api.PassThroughAuthenticationHandlerApi;
import com.konfigthis.client.api.PassphraseProviderApi;
import com.konfigthis.client.api.PasswordGeneratorApi;
import com.konfigthis.client.api.PasswordPolicyApi;
import com.konfigthis.client.api.PasswordStorageSchemeApi;
import com.konfigthis.client.api.PasswordValidatorApi;
import com.konfigthis.client.api.PluginApi;
import com.konfigthis.client.api.PluginRootApi;
import com.konfigthis.client.api.PostLdifExportTaskProcessorApi;
import com.konfigthis.client.api.PrometheusMonitorAttributeMetricApi;
import com.konfigthis.client.api.RecurringTaskApi;
import com.konfigthis.client.api.RecurringTaskChainApi;
import com.konfigthis.client.api.ReplicationAssurancePolicyApi;
import com.konfigthis.client.api.ReplicationDomainApi;
import com.konfigthis.client.api.ReplicationServerApi;
import com.konfigthis.client.api.RequestCriteriaApi;
import com.konfigthis.client.api.RestResourceTypeApi;
import com.konfigthis.client.api.ResultCodeMapApi;
import com.konfigthis.client.api.ResultCriteriaApi;
import com.konfigthis.client.api.RootDnApi;
import com.konfigthis.client.api.RootDnUserApi;
import com.konfigthis.client.api.RootDseBackendApi;
import com.konfigthis.client.api.SaslMechanismHandlerApi;
import com.konfigthis.client.api.ScimAttributeApi;
import com.konfigthis.client.api.ScimAttributeMappingApi;
import com.konfigthis.client.api.ScimResourceTypeApi;
import com.konfigthis.client.api.ScimSchemaApi;
import com.konfigthis.client.api.ScimSubattributeApi;
import com.konfigthis.client.api.SearchEntryCriteriaApi;
import com.konfigthis.client.api.SearchReferenceCriteriaApi;
import com.konfigthis.client.api.SensitiveAttributeApi;
import com.konfigthis.client.api.ServerGroupApi;
import com.konfigthis.client.api.ServerInstanceApi;
import com.konfigthis.client.api.ServerInstanceListenerApi;
import com.konfigthis.client.api.SoftDeletePolicyApi;
import com.konfigthis.client.api.SynchronizationProviderApi;
import com.konfigthis.client.api.TokenClaimValidationApi;
import com.konfigthis.client.api.TopologyAdminUserApi;
import com.konfigthis.client.api.TrustManagerProviderApi;
import com.konfigthis.client.api.TrustedCertificateApi;
import com.konfigthis.client.api.UncachedAttributeCriteriaApi;
import com.konfigthis.client.api.UncachedEntryCriteriaApi;
import com.konfigthis.client.api.VaultAuthenticationMethodApi;
import com.konfigthis.client.api.VelocityContextProviderApi;
import com.konfigthis.client.api.VelocityTemplateLoaderApi;
import com.konfigthis.client.api.VirtualAttributeApi;
import com.konfigthis.client.api.WebApplicationExtensionApi;
import com.konfigthis.client.api.WorkQueueApi;

public class PingIdentityDirectory {
    private ApiClient apiClient;
    public final AccessControlHandlerApi accessControlHandler;
    public final AccessTokenValidatorApi accessTokenValidator;
    public final AccountStatusNotificationHandlerApi accountStatusNotificationHandler;
    public final AlarmManagerApi alarmManager;
    public final AlertHandlerApi alertHandler;
    public final AttributeSyntaxApi attributeSyntax;
    public final AzureAuthenticationMethodApi azureAuthenticationMethod;
    public final BackendApi backend;
    public final CertificateMapperApi certificateMapper;
    public final ChangeSubscriptionApi changeSubscription;
    public final ChangeSubscriptionHandlerApi changeSubscriptionHandler;
    public final CipherSecretKeyApi cipherSecretKey;
    public final CipherStreamProviderApi cipherStreamProvider;
    public final ClientConnectionPolicyApi clientConnectionPolicy;
    public final ConjurAuthenticationMethodApi conjurAuthenticationMethod;
    public final ConnectionCriteriaApi connectionCriteria;
    public final ConnectionHandlerApi connectionHandler;
    public final ConsentDefinitionApi consentDefinition;
    public final ConsentDefinitionLocalizationApi consentDefinitionLocalization;
    public final ConsentServiceApi consentService;
    public final ConstructedAttributeApi constructedAttribute;
    public final CorrelatedLdapDataViewApi correlatedLdapDataView;
    public final CryptoManagerApi cryptoManager;
    public final CustomLoggedStatsApi customLoggedStats;
    public final DataSecurityAuditorApi dataSecurityAuditor;
    public final DebugTargetApi debugTarget;
    public final DelegatedAdminAttributeApi delegatedAdminAttribute;
    public final DelegatedAdminAttributeCategoryApi delegatedAdminAttributeCategory;
    public final DelegatedAdminCorrelatedRestResourceApi delegatedAdminCorrelatedRestResource;
    public final DelegatedAdminResourceRightsApi delegatedAdminResourceRights;
    public final DelegatedAdminRightsApi delegatedAdminRights;
    public final DnMapApi dnMap;
    public final EntryCacheApi entryCache;
    public final ExtendedOperationHandlerApi extendedOperationHandler;
    public final ExternalServerApi externalServer;
    public final FailureLockoutActionApi failureLockoutAction;
    public final GaugeApi gauge;
    public final GaugeDataSourceApi gaugeDataSource;
    public final GlobalConfigurationApi globalConfiguration;
    public final GroupImplementationApi groupImplementation;
    public final HttpConfigurationApi httpConfiguration;
    public final HttpServletCrossOriginPolicyApi httpServletCrossOriginPolicy;
    public final HttpServletExtensionApi httpServletExtension;
    public final IdTokenValidatorApi idTokenValidator;
    public final IdentityMapperApi identityMapper;
    public final InterServerAuthenticationInfoApi interServerAuthenticationInfo;
    public final JsonAttributeConstraintsApi jsonAttributeConstraints;
    public final JsonFieldConstraintsApi jsonFieldConstraints;
    public final KeyManagerProviderApi keyManagerProvider;
    public final KeyPairApi keyPair;
    public final LdapCorrelationAttributePairApi ldapCorrelationAttributePair;
    public final LdapSdkDebugLoggerApi ldapSdkDebugLogger;
    public final LicenseApi license;
    public final LocalDbCompositeIndexApi localDbCompositeIndex;
    public final LocalDbIndexApi localDbIndex;
    public final LocalDbVlvIndexApi localDbVlvIndex;
    public final LocationApi location;
    public final LogFieldBehaviorApi logFieldBehavior;
    public final LogFieldMappingApi logFieldMapping;
    public final LogFieldSyntaxApi logFieldSyntax;
    public final LogFileRotationListenerApi logFileRotationListener;
    public final LogPublisherApi logPublisher;
    public final LogRetentionPolicyApi logRetentionPolicy;
    public final LogRotationPolicyApi logRotationPolicy;
    public final MacSecretKeyApi macSecretKey;
    public final MatchingRuleApi matchingRule;
    public final MonitorProviderApi monitorProvider;
    public final MonitoringEndpointApi monitoringEndpoint;
    public final NotificationManagerApi notificationManager;
    public final OauthTokenHandlerApi oauthTokenHandler;
    public final ObscuredValueApi obscuredValue;
    public final OtpDeliveryMechanismApi otpDeliveryMechanism;
    public final PassThroughAuthenticationHandlerApi passThroughAuthenticationHandler;
    public final PassphraseProviderApi passphraseProvider;
    public final PasswordGeneratorApi passwordGenerator;
    public final PasswordPolicyApi passwordPolicy;
    public final PasswordStorageSchemeApi passwordStorageScheme;
    public final PasswordValidatorApi passwordValidator;
    public final PluginApi plugin;
    public final PluginRootApi pluginRoot;
    public final PostLdifExportTaskProcessorApi postLdifExportTaskProcessor;
    public final PrometheusMonitorAttributeMetricApi prometheusMonitorAttributeMetric;
    public final RecurringTaskApi recurringTask;
    public final RecurringTaskChainApi recurringTaskChain;
    public final ReplicationAssurancePolicyApi replicationAssurancePolicy;
    public final ReplicationDomainApi replicationDomain;
    public final ReplicationServerApi replicationServer;
    public final RequestCriteriaApi requestCriteria;
    public final RestResourceTypeApi restResourceType;
    public final ResultCodeMapApi resultCodeMap;
    public final ResultCriteriaApi resultCriteria;
    public final RootDnApi rootDn;
    public final RootDnUserApi rootDnUser;
    public final RootDseBackendApi rootDseBackend;
    public final SaslMechanismHandlerApi saslMechanismHandler;
    public final ScimAttributeApi scimAttribute;
    public final ScimAttributeMappingApi scimAttributeMapping;
    public final ScimResourceTypeApi scimResourceType;
    public final ScimSchemaApi scimSchema;
    public final ScimSubattributeApi scimSubattribute;
    public final SearchEntryCriteriaApi searchEntryCriteria;
    public final SearchReferenceCriteriaApi searchReferenceCriteria;
    public final SensitiveAttributeApi sensitiveAttribute;
    public final ServerGroupApi serverGroup;
    public final ServerInstanceApi serverInstance;
    public final ServerInstanceListenerApi serverInstanceListener;
    public final SoftDeletePolicyApi softDeletePolicy;
    public final SynchronizationProviderApi synchronizationProvider;
    public final TokenClaimValidationApi tokenClaimValidation;
    public final TopologyAdminUserApi topologyAdminUser;
    public final TrustManagerProviderApi trustManagerProvider;
    public final TrustedCertificateApi trustedCertificate;
    public final UncachedAttributeCriteriaApi uncachedAttributeCriteria;
    public final UncachedEntryCriteriaApi uncachedEntryCriteria;
    public final VaultAuthenticationMethodApi vaultAuthenticationMethod;
    public final VelocityContextProviderApi velocityContextProvider;
    public final VelocityTemplateLoaderApi velocityTemplateLoader;
    public final VirtualAttributeApi virtualAttribute;
    public final WebApplicationExtensionApi webApplicationExtension;
    public final WorkQueueApi workQueue;

    public PingIdentityDirectory() {
        this(null);
    }

    public PingIdentityDirectory(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.accessControlHandler = new AccessControlHandlerApi(this.apiClient);
        this.accessTokenValidator = new AccessTokenValidatorApi(this.apiClient);
        this.accountStatusNotificationHandler = new AccountStatusNotificationHandlerApi(this.apiClient);
        this.alarmManager = new AlarmManagerApi(this.apiClient);
        this.alertHandler = new AlertHandlerApi(this.apiClient);
        this.attributeSyntax = new AttributeSyntaxApi(this.apiClient);
        this.azureAuthenticationMethod = new AzureAuthenticationMethodApi(this.apiClient);
        this.backend = new BackendApi(this.apiClient);
        this.certificateMapper = new CertificateMapperApi(this.apiClient);
        this.changeSubscription = new ChangeSubscriptionApi(this.apiClient);
        this.changeSubscriptionHandler = new ChangeSubscriptionHandlerApi(this.apiClient);
        this.cipherSecretKey = new CipherSecretKeyApi(this.apiClient);
        this.cipherStreamProvider = new CipherStreamProviderApi(this.apiClient);
        this.clientConnectionPolicy = new ClientConnectionPolicyApi(this.apiClient);
        this.conjurAuthenticationMethod = new ConjurAuthenticationMethodApi(this.apiClient);
        this.connectionCriteria = new ConnectionCriteriaApi(this.apiClient);
        this.connectionHandler = new ConnectionHandlerApi(this.apiClient);
        this.consentDefinition = new ConsentDefinitionApi(this.apiClient);
        this.consentDefinitionLocalization = new ConsentDefinitionLocalizationApi(this.apiClient);
        this.consentService = new ConsentServiceApi(this.apiClient);
        this.constructedAttribute = new ConstructedAttributeApi(this.apiClient);
        this.correlatedLdapDataView = new CorrelatedLdapDataViewApi(this.apiClient);
        this.cryptoManager = new CryptoManagerApi(this.apiClient);
        this.customLoggedStats = new CustomLoggedStatsApi(this.apiClient);
        this.dataSecurityAuditor = new DataSecurityAuditorApi(this.apiClient);
        this.debugTarget = new DebugTargetApi(this.apiClient);
        this.delegatedAdminAttribute = new DelegatedAdminAttributeApi(this.apiClient);
        this.delegatedAdminAttributeCategory = new DelegatedAdminAttributeCategoryApi(this.apiClient);
        this.delegatedAdminCorrelatedRestResource = new DelegatedAdminCorrelatedRestResourceApi(this.apiClient);
        this.delegatedAdminResourceRights = new DelegatedAdminResourceRightsApi(this.apiClient);
        this.delegatedAdminRights = new DelegatedAdminRightsApi(this.apiClient);
        this.dnMap = new DnMapApi(this.apiClient);
        this.entryCache = new EntryCacheApi(this.apiClient);
        this.extendedOperationHandler = new ExtendedOperationHandlerApi(this.apiClient);
        this.externalServer = new ExternalServerApi(this.apiClient);
        this.failureLockoutAction = new FailureLockoutActionApi(this.apiClient);
        this.gauge = new GaugeApi(this.apiClient);
        this.gaugeDataSource = new GaugeDataSourceApi(this.apiClient);
        this.globalConfiguration = new GlobalConfigurationApi(this.apiClient);
        this.groupImplementation = new GroupImplementationApi(this.apiClient);
        this.httpConfiguration = new HttpConfigurationApi(this.apiClient);
        this.httpServletCrossOriginPolicy = new HttpServletCrossOriginPolicyApi(this.apiClient);
        this.httpServletExtension = new HttpServletExtensionApi(this.apiClient);
        this.idTokenValidator = new IdTokenValidatorApi(this.apiClient);
        this.identityMapper = new IdentityMapperApi(this.apiClient);
        this.interServerAuthenticationInfo = new InterServerAuthenticationInfoApi(this.apiClient);
        this.jsonAttributeConstraints = new JsonAttributeConstraintsApi(this.apiClient);
        this.jsonFieldConstraints = new JsonFieldConstraintsApi(this.apiClient);
        this.keyManagerProvider = new KeyManagerProviderApi(this.apiClient);
        this.keyPair = new KeyPairApi(this.apiClient);
        this.ldapCorrelationAttributePair = new LdapCorrelationAttributePairApi(this.apiClient);
        this.ldapSdkDebugLogger = new LdapSdkDebugLoggerApi(this.apiClient);
        this.license = new LicenseApi(this.apiClient);
        this.localDbCompositeIndex = new LocalDbCompositeIndexApi(this.apiClient);
        this.localDbIndex = new LocalDbIndexApi(this.apiClient);
        this.localDbVlvIndex = new LocalDbVlvIndexApi(this.apiClient);
        this.location = new LocationApi(this.apiClient);
        this.logFieldBehavior = new LogFieldBehaviorApi(this.apiClient);
        this.logFieldMapping = new LogFieldMappingApi(this.apiClient);
        this.logFieldSyntax = new LogFieldSyntaxApi(this.apiClient);
        this.logFileRotationListener = new LogFileRotationListenerApi(this.apiClient);
        this.logPublisher = new LogPublisherApi(this.apiClient);
        this.logRetentionPolicy = new LogRetentionPolicyApi(this.apiClient);
        this.logRotationPolicy = new LogRotationPolicyApi(this.apiClient);
        this.macSecretKey = new MacSecretKeyApi(this.apiClient);
        this.matchingRule = new MatchingRuleApi(this.apiClient);
        this.monitorProvider = new MonitorProviderApi(this.apiClient);
        this.monitoringEndpoint = new MonitoringEndpointApi(this.apiClient);
        this.notificationManager = new NotificationManagerApi(this.apiClient);
        this.oauthTokenHandler = new OauthTokenHandlerApi(this.apiClient);
        this.obscuredValue = new ObscuredValueApi(this.apiClient);
        this.otpDeliveryMechanism = new OtpDeliveryMechanismApi(this.apiClient);
        this.passThroughAuthenticationHandler = new PassThroughAuthenticationHandlerApi(this.apiClient);
        this.passphraseProvider = new PassphraseProviderApi(this.apiClient);
        this.passwordGenerator = new PasswordGeneratorApi(this.apiClient);
        this.passwordPolicy = new PasswordPolicyApi(this.apiClient);
        this.passwordStorageScheme = new PasswordStorageSchemeApi(this.apiClient);
        this.passwordValidator = new PasswordValidatorApi(this.apiClient);
        this.plugin = new PluginApi(this.apiClient);
        this.pluginRoot = new PluginRootApi(this.apiClient);
        this.postLdifExportTaskProcessor = new PostLdifExportTaskProcessorApi(this.apiClient);
        this.prometheusMonitorAttributeMetric = new PrometheusMonitorAttributeMetricApi(this.apiClient);
        this.recurringTask = new RecurringTaskApi(this.apiClient);
        this.recurringTaskChain = new RecurringTaskChainApi(this.apiClient);
        this.replicationAssurancePolicy = new ReplicationAssurancePolicyApi(this.apiClient);
        this.replicationDomain = new ReplicationDomainApi(this.apiClient);
        this.replicationServer = new ReplicationServerApi(this.apiClient);
        this.requestCriteria = new RequestCriteriaApi(this.apiClient);
        this.restResourceType = new RestResourceTypeApi(this.apiClient);
        this.resultCodeMap = new ResultCodeMapApi(this.apiClient);
        this.resultCriteria = new ResultCriteriaApi(this.apiClient);
        this.rootDn = new RootDnApi(this.apiClient);
        this.rootDnUser = new RootDnUserApi(this.apiClient);
        this.rootDseBackend = new RootDseBackendApi(this.apiClient);
        this.saslMechanismHandler = new SaslMechanismHandlerApi(this.apiClient);
        this.scimAttribute = new ScimAttributeApi(this.apiClient);
        this.scimAttributeMapping = new ScimAttributeMappingApi(this.apiClient);
        this.scimResourceType = new ScimResourceTypeApi(this.apiClient);
        this.scimSchema = new ScimSchemaApi(this.apiClient);
        this.scimSubattribute = new ScimSubattributeApi(this.apiClient);
        this.searchEntryCriteria = new SearchEntryCriteriaApi(this.apiClient);
        this.searchReferenceCriteria = new SearchReferenceCriteriaApi(this.apiClient);
        this.sensitiveAttribute = new SensitiveAttributeApi(this.apiClient);
        this.serverGroup = new ServerGroupApi(this.apiClient);
        this.serverInstance = new ServerInstanceApi(this.apiClient);
        this.serverInstanceListener = new ServerInstanceListenerApi(this.apiClient);
        this.softDeletePolicy = new SoftDeletePolicyApi(this.apiClient);
        this.synchronizationProvider = new SynchronizationProviderApi(this.apiClient);
        this.tokenClaimValidation = new TokenClaimValidationApi(this.apiClient);
        this.topologyAdminUser = new TopologyAdminUserApi(this.apiClient);
        this.trustManagerProvider = new TrustManagerProviderApi(this.apiClient);
        this.trustedCertificate = new TrustedCertificateApi(this.apiClient);
        this.uncachedAttributeCriteria = new UncachedAttributeCriteriaApi(this.apiClient);
        this.uncachedEntryCriteria = new UncachedEntryCriteriaApi(this.apiClient);
        this.vaultAuthenticationMethod = new VaultAuthenticationMethodApi(this.apiClient);
        this.velocityContextProvider = new VelocityContextProviderApi(this.apiClient);
        this.velocityTemplateLoader = new VelocityTemplateLoaderApi(this.apiClient);
        this.virtualAttribute = new VirtualAttributeApi(this.apiClient);
        this.webApplicationExtension = new WebApplicationExtensionApi(this.apiClient);
        this.workQueue = new WorkQueueApi(this.apiClient);
    }

}
