/*
 * PingData Config - OpenAPI 3.0
 * This is the PingData Configuration API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EnumgroovyScriptedPasswordValidatorSchemaUrn
 */
public class EnumgroovyScriptedPasswordValidatorSchemaUrnTest {
    /**
     * Model tests for EnumgroovyScriptedPasswordValidatorSchemaUrn
     */
    @Test
    public void testEnumgroovyScriptedPasswordValidatorSchemaUrn() {
        // TODO: test EnumgroovyScriptedPasswordValidatorSchemaUrn
    }

}
