/*
 * PingData Config - OpenAPI 3.0
 * This is the PingData Configuration API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EnumlicenseSchemaUrn;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LicenseResponseAllOf
 */
public class LicenseResponseAllOfTest {
    private final LicenseResponseAllOf model = new LicenseResponseAllOf();

    /**
     * Model tests for LicenseResponseAllOf
     */
    @Test
    public void testLicenseResponseAllOf() {
        // TODO: test LicenseResponseAllOf
    }

    /**
     * Test the property 'schemas'
     */
    @Test
    public void schemasTest() {
        // TODO: test schemas
    }

    /**
     * Test the property 'directoryPlatformLicenseKey'
     */
    @Test
    public void directoryPlatformLicenseKeyTest() {
        // TODO: test directoryPlatformLicenseKey
    }

}
