/*
 * PingData Config - OpenAPI 3.0
 * This is the PingData Configuration API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Specifies the circumstances under which the values of the sub-attribute are returned in response to a request.
 */
@JsonAdapter(EnumscimSubattributeReturnedProp.Adapter.class)public enum EnumscimSubattributeReturnedProp {
  
  BY_DEFAULT("by-default"),
  
  UPON_REQUEST("upon-request"),
  
  ALWAYS("always"),
  
  NEVER("never");

  private String value;

  EnumscimSubattributeReturnedProp(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnumscimSubattributeReturnedProp fromValue(String value) {
    for (EnumscimSubattributeReturnedProp b : EnumscimSubattributeReturnedProp.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EnumscimSubattributeReturnedProp> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnumscimSubattributeReturnedProp enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnumscimSubattributeReturnedProp read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnumscimSubattributeReturnedProp.fromValue(value);
    }
  }
}

